drop policy "get" on "public"."beers";

drop policy "get" on "public"."beers_flavors";

drop policy "get" on "public"."beers_taste";

drop policy "get" on "public"."foods";

drop policy "get" on "public"."locations";

drop policy "get" on "public"."materials";

drop policy "get" on "public"."orders";

drop policy "get" on "public"."softs";

drop policy "get" on "public"."stock_beers";

drop policy "get" on "public"."stock_foods";

drop policy "get" on "public"."stock_materials";

drop policy "get" on "public"."stock_softs";


  create table "public"."coffee" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "image" text not null,
    "price" numeric not null,
    "price_large" numeric
      );


alter table "public"."coffee" enable row level security;

CREATE UNIQUE INDEX coffee_pkey ON public.coffee USING btree (id);

alter table "public"."coffee" add constraint "coffee_pkey" PRIMARY KEY using index "coffee_pkey";

grant delete on table "public"."coffee" to "anon";

grant insert on table "public"."coffee" to "anon";

grant references on table "public"."coffee" to "anon";

grant select on table "public"."coffee" to "anon";

grant trigger on table "public"."coffee" to "anon";

grant truncate on table "public"."coffee" to "anon";

grant update on table "public"."coffee" to "anon";

grant delete on table "public"."coffee" to "authenticated";

grant insert on table "public"."coffee" to "authenticated";

grant references on table "public"."coffee" to "authenticated";

grant select on table "public"."coffee" to "authenticated";

grant trigger on table "public"."coffee" to "authenticated";

grant truncate on table "public"."coffee" to "authenticated";

grant update on table "public"."coffee" to "authenticated";

grant delete on table "public"."coffee" to "service_role";

grant insert on table "public"."coffee" to "service_role";

grant references on table "public"."coffee" to "service_role";

grant select on table "public"."coffee" to "service_role";

grant trigger on table "public"."coffee" to "service_role";

grant truncate on table "public"."coffee" to "service_role";

grant update on table "public"."coffee" to "service_role";


  create policy "Enable read access for all users"
  on "public"."beers"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."beers_flavors"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."beers_taste"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."coffee"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."foods"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."locations"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."materials"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."orders"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."softs"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."stock_beers"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."stock_foods"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."stock_materials"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."stock_softs"
  as permissive
  for select
  to public
using (true);



