
  create table "public"."beers" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "image" text,
    "volume" numeric not null default 0.0,
    "alcohol" numeric not null default 0.0,
    "type" text,
    "description" text,
    "price" numeric not null default '0'::numeric
      );


alter table "public"."beers" enable row level security;


  create table "public"."beers_flavors" (
    "id" bigint generated by default as identity not null,
    "visual" text,
    "smell" text,
    "taste" text
      );


alter table "public"."beers_flavors" enable row level security;


  create table "public"."beers_taste" (
    "id" bigint generated by default as identity not null,
    "bitterness" numeric default '0'::numeric,
    "power" numeric default '0'::numeric,
    "roundness" numeric default '0'::numeric,
    "fruity" numeric default '0'::numeric,
    "liveliness" numeric default '0'::numeric,
    "acidity" numeric default '0'::numeric
      );


alter table "public"."beers_taste" enable row level security;


  create table "public"."foods" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "ingredients" text,
    "image" text,
    "price" numeric not null
      );


alter table "public"."foods" enable row level security;


  create table "public"."locations" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "prefix" text not null,
    "orders" numeric not null default '0'::numeric
      );


alter table "public"."locations" enable row level security;


  create table "public"."materials" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text,
    "image" text,
    "price" numeric not null default '0'::numeric
      );


alter table "public"."materials" enable row level security;


  create table "public"."orders" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "location" bigint not null,
    "name" text not null,
    "order" json not null,
    "status" text not null
      );


alter table "public"."orders" enable row level security;


  create table "public"."softs" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "volume" numeric not null,
    "image" text,
    "price" numeric not null
      );


alter table "public"."softs" enable row level security;


  create table "public"."stock_beers" (
    "id" bigint generated by default as identity not null,
    "bottles_per_crate" numeric not null default '0'::numeric,
    "stock_crates" numeric not null default '0'::numeric
      );


alter table "public"."stock_beers" enable row level security;


  create table "public"."stock_foods" (
    "id" bigint generated by default as identity not null,
    "entity_per_box" numeric not null,
    "stock_box" numeric not null default '0'::numeric
      );


alter table "public"."stock_foods" enable row level security;


  create table "public"."stock_materials" (
    "id" bigint generated by default as identity not null,
    "entity_per_box" numeric not null,
    "stock_box" numeric not null default '0'::numeric
      );


alter table "public"."stock_materials" enable row level security;


  create table "public"."stock_softs" (
    "id" bigint generated by default as identity not null,
    "bottles_per_crate" numeric not null,
    "stock_crates" numeric not null
      );


alter table "public"."stock_softs" enable row level security;

CREATE UNIQUE INDEX beers_flavors_pkey ON public.beers_flavors USING btree (id);

CREATE UNIQUE INDEX beers_name_key ON public.beers USING btree (name);

CREATE UNIQUE INDEX beers_pkey ON public.beers USING btree (id);

CREATE UNIQUE INDEX beers_taste_pkey ON public.beers_taste USING btree (id);

CREATE UNIQUE INDEX foods_pkey ON public.foods USING btree (id);

CREATE UNIQUE INDEX locations_name_key ON public.locations USING btree (name);

CREATE UNIQUE INDEX locations_pkey ON public.locations USING btree (id);

CREATE UNIQUE INDEX locations_prefix_key ON public.locations USING btree (prefix);

CREATE UNIQUE INDEX materials_pkey ON public.materials USING btree (id);

CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (id);

CREATE UNIQUE INDEX softs_pkey ON public.softs USING btree (id);

CREATE UNIQUE INDEX stock_beers_pkey ON public.stock_beers USING btree (id);

CREATE UNIQUE INDEX stock_foods_pkey ON public.stock_foods USING btree (id);

CREATE UNIQUE INDEX stock_materials_pkey ON public.stock_materials USING btree (id);

CREATE UNIQUE INDEX stock_softs_pkey ON public.stock_softs USING btree (id);

alter table "public"."beers" add constraint "beers_pkey" PRIMARY KEY using index "beers_pkey";

alter table "public"."beers_flavors" add constraint "beers_flavors_pkey" PRIMARY KEY using index "beers_flavors_pkey";

alter table "public"."beers_taste" add constraint "beers_taste_pkey" PRIMARY KEY using index "beers_taste_pkey";

alter table "public"."foods" add constraint "foods_pkey" PRIMARY KEY using index "foods_pkey";

alter table "public"."locations" add constraint "locations_pkey" PRIMARY KEY using index "locations_pkey";

alter table "public"."materials" add constraint "materials_pkey" PRIMARY KEY using index "materials_pkey";

alter table "public"."orders" add constraint "orders_pkey" PRIMARY KEY using index "orders_pkey";

alter table "public"."softs" add constraint "softs_pkey" PRIMARY KEY using index "softs_pkey";

alter table "public"."stock_beers" add constraint "stock_beers_pkey" PRIMARY KEY using index "stock_beers_pkey";

alter table "public"."stock_foods" add constraint "stock_foods_pkey" PRIMARY KEY using index "stock_foods_pkey";

alter table "public"."stock_materials" add constraint "stock_materials_pkey" PRIMARY KEY using index "stock_materials_pkey";

alter table "public"."stock_softs" add constraint "stock_softs_pkey" PRIMARY KEY using index "stock_softs_pkey";

alter table "public"."beers" add constraint "beers_name_key" UNIQUE using index "beers_name_key";

alter table "public"."beers" add constraint "beers_price_check" CHECK ((price > (0)::numeric)) not valid;

alter table "public"."beers" validate constraint "beers_price_check";

alter table "public"."beers_flavors" add constraint "beers_flavors_id_fkey" FOREIGN KEY (id) REFERENCES public.beers(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."beers_flavors" validate constraint "beers_flavors_id_fkey";

alter table "public"."beers_taste" add constraint "beers_taste_id_fkey" FOREIGN KEY (id) REFERENCES public.beers(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."beers_taste" validate constraint "beers_taste_id_fkey";

alter table "public"."locations" add constraint "locations_name_key" UNIQUE using index "locations_name_key";

alter table "public"."locations" add constraint "locations_prefix_key" UNIQUE using index "locations_prefix_key";

alter table "public"."orders" add constraint "orders_location_fkey" FOREIGN KEY (location) REFERENCES public.locations(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."orders" validate constraint "orders_location_fkey";

alter table "public"."stock_beers" add constraint "stock_beers_id_fkey" FOREIGN KEY (id) REFERENCES public.beers(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."stock_beers" validate constraint "stock_beers_id_fkey";

alter table "public"."stock_foods" add constraint "stock_foods_id_fkey" FOREIGN KEY (id) REFERENCES public.foods(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."stock_foods" validate constraint "stock_foods_id_fkey";

alter table "public"."stock_materials" add constraint "stock_materials_id_fkey" FOREIGN KEY (id) REFERENCES public.materials(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."stock_materials" validate constraint "stock_materials_id_fkey";

alter table "public"."stock_softs" add constraint "stock_softs_id_fkey" FOREIGN KEY (id) REFERENCES public.softs(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."stock_softs" validate constraint "stock_softs_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_public_tables()
 RETURNS TABLE(table_name text)
 LANGUAGE plpgsql
 STABLE
AS $function$
BEGIN
    RETURN QUERY
    SELECT tablename AS table_name  -- Le nom de la colonne doit être exactement "table_name"
    FROM pg_catalog.pg_tables
    WHERE schemaname = 'public';
END;
$function$
;

CREATE OR REPLACE FUNCTION public.pg_execute(sql text)
 RETURNS SETOF record
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    RETURN QUERY EXECUTE sql;
END;
$function$
;

grant delete on table "public"."beers" to "anon";

grant insert on table "public"."beers" to "anon";

grant references on table "public"."beers" to "anon";

grant select on table "public"."beers" to "anon";

grant trigger on table "public"."beers" to "anon";

grant truncate on table "public"."beers" to "anon";

grant update on table "public"."beers" to "anon";

grant delete on table "public"."beers" to "authenticated";

grant insert on table "public"."beers" to "authenticated";

grant references on table "public"."beers" to "authenticated";

grant select on table "public"."beers" to "authenticated";

grant trigger on table "public"."beers" to "authenticated";

grant truncate on table "public"."beers" to "authenticated";

grant update on table "public"."beers" to "authenticated";

grant delete on table "public"."beers" to "service_role";

grant insert on table "public"."beers" to "service_role";

grant references on table "public"."beers" to "service_role";

grant select on table "public"."beers" to "service_role";

grant trigger on table "public"."beers" to "service_role";

grant truncate on table "public"."beers" to "service_role";

grant update on table "public"."beers" to "service_role";

grant delete on table "public"."beers_flavors" to "anon";

grant insert on table "public"."beers_flavors" to "anon";

grant references on table "public"."beers_flavors" to "anon";

grant select on table "public"."beers_flavors" to "anon";

grant trigger on table "public"."beers_flavors" to "anon";

grant truncate on table "public"."beers_flavors" to "anon";

grant update on table "public"."beers_flavors" to "anon";

grant delete on table "public"."beers_flavors" to "authenticated";

grant insert on table "public"."beers_flavors" to "authenticated";

grant references on table "public"."beers_flavors" to "authenticated";

grant select on table "public"."beers_flavors" to "authenticated";

grant trigger on table "public"."beers_flavors" to "authenticated";

grant truncate on table "public"."beers_flavors" to "authenticated";

grant update on table "public"."beers_flavors" to "authenticated";

grant delete on table "public"."beers_flavors" to "service_role";

grant insert on table "public"."beers_flavors" to "service_role";

grant references on table "public"."beers_flavors" to "service_role";

grant select on table "public"."beers_flavors" to "service_role";

grant trigger on table "public"."beers_flavors" to "service_role";

grant truncate on table "public"."beers_flavors" to "service_role";

grant update on table "public"."beers_flavors" to "service_role";

grant delete on table "public"."beers_taste" to "anon";

grant insert on table "public"."beers_taste" to "anon";

grant references on table "public"."beers_taste" to "anon";

grant select on table "public"."beers_taste" to "anon";

grant trigger on table "public"."beers_taste" to "anon";

grant truncate on table "public"."beers_taste" to "anon";

grant update on table "public"."beers_taste" to "anon";

grant delete on table "public"."beers_taste" to "authenticated";

grant insert on table "public"."beers_taste" to "authenticated";

grant references on table "public"."beers_taste" to "authenticated";

grant select on table "public"."beers_taste" to "authenticated";

grant trigger on table "public"."beers_taste" to "authenticated";

grant truncate on table "public"."beers_taste" to "authenticated";

grant update on table "public"."beers_taste" to "authenticated";

grant delete on table "public"."beers_taste" to "service_role";

grant insert on table "public"."beers_taste" to "service_role";

grant references on table "public"."beers_taste" to "service_role";

grant select on table "public"."beers_taste" to "service_role";

grant trigger on table "public"."beers_taste" to "service_role";

grant truncate on table "public"."beers_taste" to "service_role";

grant update on table "public"."beers_taste" to "service_role";

grant delete on table "public"."foods" to "anon";

grant insert on table "public"."foods" to "anon";

grant references on table "public"."foods" to "anon";

grant select on table "public"."foods" to "anon";

grant trigger on table "public"."foods" to "anon";

grant truncate on table "public"."foods" to "anon";

grant update on table "public"."foods" to "anon";

grant delete on table "public"."foods" to "authenticated";

grant insert on table "public"."foods" to "authenticated";

grant references on table "public"."foods" to "authenticated";

grant select on table "public"."foods" to "authenticated";

grant trigger on table "public"."foods" to "authenticated";

grant truncate on table "public"."foods" to "authenticated";

grant update on table "public"."foods" to "authenticated";

grant delete on table "public"."foods" to "service_role";

grant insert on table "public"."foods" to "service_role";

grant references on table "public"."foods" to "service_role";

grant select on table "public"."foods" to "service_role";

grant trigger on table "public"."foods" to "service_role";

grant truncate on table "public"."foods" to "service_role";

grant update on table "public"."foods" to "service_role";

grant delete on table "public"."locations" to "anon";

grant insert on table "public"."locations" to "anon";

grant references on table "public"."locations" to "anon";

grant select on table "public"."locations" to "anon";

grant trigger on table "public"."locations" to "anon";

grant truncate on table "public"."locations" to "anon";

grant update on table "public"."locations" to "anon";

grant delete on table "public"."locations" to "authenticated";

grant insert on table "public"."locations" to "authenticated";

grant references on table "public"."locations" to "authenticated";

grant select on table "public"."locations" to "authenticated";

grant trigger on table "public"."locations" to "authenticated";

grant truncate on table "public"."locations" to "authenticated";

grant update on table "public"."locations" to "authenticated";

grant delete on table "public"."locations" to "service_role";

grant insert on table "public"."locations" to "service_role";

grant references on table "public"."locations" to "service_role";

grant select on table "public"."locations" to "service_role";

grant trigger on table "public"."locations" to "service_role";

grant truncate on table "public"."locations" to "service_role";

grant update on table "public"."locations" to "service_role";

grant delete on table "public"."materials" to "anon";

grant insert on table "public"."materials" to "anon";

grant references on table "public"."materials" to "anon";

grant select on table "public"."materials" to "anon";

grant trigger on table "public"."materials" to "anon";

grant truncate on table "public"."materials" to "anon";

grant update on table "public"."materials" to "anon";

grant delete on table "public"."materials" to "authenticated";

grant insert on table "public"."materials" to "authenticated";

grant references on table "public"."materials" to "authenticated";

grant select on table "public"."materials" to "authenticated";

grant trigger on table "public"."materials" to "authenticated";

grant truncate on table "public"."materials" to "authenticated";

grant update on table "public"."materials" to "authenticated";

grant delete on table "public"."materials" to "service_role";

grant insert on table "public"."materials" to "service_role";

grant references on table "public"."materials" to "service_role";

grant select on table "public"."materials" to "service_role";

grant trigger on table "public"."materials" to "service_role";

grant truncate on table "public"."materials" to "service_role";

grant update on table "public"."materials" to "service_role";

grant delete on table "public"."orders" to "anon";

grant insert on table "public"."orders" to "anon";

grant references on table "public"."orders" to "anon";

grant select on table "public"."orders" to "anon";

grant trigger on table "public"."orders" to "anon";

grant truncate on table "public"."orders" to "anon";

grant update on table "public"."orders" to "anon";

grant delete on table "public"."orders" to "authenticated";

grant insert on table "public"."orders" to "authenticated";

grant references on table "public"."orders" to "authenticated";

grant select on table "public"."orders" to "authenticated";

grant trigger on table "public"."orders" to "authenticated";

grant truncate on table "public"."orders" to "authenticated";

grant update on table "public"."orders" to "authenticated";

grant delete on table "public"."orders" to "service_role";

grant insert on table "public"."orders" to "service_role";

grant references on table "public"."orders" to "service_role";

grant select on table "public"."orders" to "service_role";

grant trigger on table "public"."orders" to "service_role";

grant truncate on table "public"."orders" to "service_role";

grant update on table "public"."orders" to "service_role";

grant delete on table "public"."softs" to "anon";

grant insert on table "public"."softs" to "anon";

grant references on table "public"."softs" to "anon";

grant select on table "public"."softs" to "anon";

grant trigger on table "public"."softs" to "anon";

grant truncate on table "public"."softs" to "anon";

grant update on table "public"."softs" to "anon";

grant delete on table "public"."softs" to "authenticated";

grant insert on table "public"."softs" to "authenticated";

grant references on table "public"."softs" to "authenticated";

grant select on table "public"."softs" to "authenticated";

grant trigger on table "public"."softs" to "authenticated";

grant truncate on table "public"."softs" to "authenticated";

grant update on table "public"."softs" to "authenticated";

grant delete on table "public"."softs" to "service_role";

grant insert on table "public"."softs" to "service_role";

grant references on table "public"."softs" to "service_role";

grant select on table "public"."softs" to "service_role";

grant trigger on table "public"."softs" to "service_role";

grant truncate on table "public"."softs" to "service_role";

grant update on table "public"."softs" to "service_role";

grant delete on table "public"."stock_beers" to "anon";

grant insert on table "public"."stock_beers" to "anon";

grant references on table "public"."stock_beers" to "anon";

grant select on table "public"."stock_beers" to "anon";

grant trigger on table "public"."stock_beers" to "anon";

grant truncate on table "public"."stock_beers" to "anon";

grant update on table "public"."stock_beers" to "anon";

grant delete on table "public"."stock_beers" to "authenticated";

grant insert on table "public"."stock_beers" to "authenticated";

grant references on table "public"."stock_beers" to "authenticated";

grant select on table "public"."stock_beers" to "authenticated";

grant trigger on table "public"."stock_beers" to "authenticated";

grant truncate on table "public"."stock_beers" to "authenticated";

grant update on table "public"."stock_beers" to "authenticated";

grant delete on table "public"."stock_beers" to "service_role";

grant insert on table "public"."stock_beers" to "service_role";

grant references on table "public"."stock_beers" to "service_role";

grant select on table "public"."stock_beers" to "service_role";

grant trigger on table "public"."stock_beers" to "service_role";

grant truncate on table "public"."stock_beers" to "service_role";

grant update on table "public"."stock_beers" to "service_role";

grant delete on table "public"."stock_foods" to "anon";

grant insert on table "public"."stock_foods" to "anon";

grant references on table "public"."stock_foods" to "anon";

grant select on table "public"."stock_foods" to "anon";

grant trigger on table "public"."stock_foods" to "anon";

grant truncate on table "public"."stock_foods" to "anon";

grant update on table "public"."stock_foods" to "anon";

grant delete on table "public"."stock_foods" to "authenticated";

grant insert on table "public"."stock_foods" to "authenticated";

grant references on table "public"."stock_foods" to "authenticated";

grant select on table "public"."stock_foods" to "authenticated";

grant trigger on table "public"."stock_foods" to "authenticated";

grant truncate on table "public"."stock_foods" to "authenticated";

grant update on table "public"."stock_foods" to "authenticated";

grant delete on table "public"."stock_foods" to "service_role";

grant insert on table "public"."stock_foods" to "service_role";

grant references on table "public"."stock_foods" to "service_role";

grant select on table "public"."stock_foods" to "service_role";

grant trigger on table "public"."stock_foods" to "service_role";

grant truncate on table "public"."stock_foods" to "service_role";

grant update on table "public"."stock_foods" to "service_role";

grant delete on table "public"."stock_materials" to "anon";

grant insert on table "public"."stock_materials" to "anon";

grant references on table "public"."stock_materials" to "anon";

grant select on table "public"."stock_materials" to "anon";

grant trigger on table "public"."stock_materials" to "anon";

grant truncate on table "public"."stock_materials" to "anon";

grant update on table "public"."stock_materials" to "anon";

grant delete on table "public"."stock_materials" to "authenticated";

grant insert on table "public"."stock_materials" to "authenticated";

grant references on table "public"."stock_materials" to "authenticated";

grant select on table "public"."stock_materials" to "authenticated";

grant trigger on table "public"."stock_materials" to "authenticated";

grant truncate on table "public"."stock_materials" to "authenticated";

grant update on table "public"."stock_materials" to "authenticated";

grant delete on table "public"."stock_materials" to "service_role";

grant insert on table "public"."stock_materials" to "service_role";

grant references on table "public"."stock_materials" to "service_role";

grant select on table "public"."stock_materials" to "service_role";

grant trigger on table "public"."stock_materials" to "service_role";

grant truncate on table "public"."stock_materials" to "service_role";

grant update on table "public"."stock_materials" to "service_role";

grant delete on table "public"."stock_softs" to "anon";

grant insert on table "public"."stock_softs" to "anon";

grant references on table "public"."stock_softs" to "anon";

grant select on table "public"."stock_softs" to "anon";

grant trigger on table "public"."stock_softs" to "anon";

grant truncate on table "public"."stock_softs" to "anon";

grant update on table "public"."stock_softs" to "anon";

grant delete on table "public"."stock_softs" to "authenticated";

grant insert on table "public"."stock_softs" to "authenticated";

grant references on table "public"."stock_softs" to "authenticated";

grant select on table "public"."stock_softs" to "authenticated";

grant trigger on table "public"."stock_softs" to "authenticated";

grant truncate on table "public"."stock_softs" to "authenticated";

grant update on table "public"."stock_softs" to "authenticated";

grant delete on table "public"."stock_softs" to "service_role";

grant insert on table "public"."stock_softs" to "service_role";

grant references on table "public"."stock_softs" to "service_role";

grant select on table "public"."stock_softs" to "service_role";

grant trigger on table "public"."stock_softs" to "service_role";

grant truncate on table "public"."stock_softs" to "service_role";

grant update on table "public"."stock_softs" to "service_role";


  create policy "get"
  on "public"."beers"
  as permissive
  for select
  to public
using (true);



  create policy "get"
  on "public"."beers_flavors"
  as permissive
  for select
  to public
using (true);



  create policy "get"
  on "public"."beers_taste"
  as permissive
  for select
  to public
using (true);



  create policy "get"
  on "public"."foods"
  as permissive
  for select
  to public
using (true);



  create policy "get"
  on "public"."locations"
  as permissive
  for select
  to public
using (true);



  create policy "get"
  on "public"."materials"
  as permissive
  for select
  to public
using (true);



  create policy "get"
  on "public"."orders"
  as permissive
  for select
  to public
using (true);



  create policy "get"
  on "public"."softs"
  as permissive
  for select
  to public
using (true);



  create policy "get"
  on "public"."stock_beers"
  as permissive
  for select
  to public
using (true);



  create policy "get"
  on "public"."stock_foods"
  as permissive
  for select
  to public
using (true);



  create policy "get"
  on "public"."stock_materials"
  as permissive
  for select
  to public
using (true);



  create policy "get"
  on "public"."stock_softs"
  as permissive
  for select
  to public
using (true);



