create type "public"."ROLE" as enum ('ADMIN', 'TREZ', 'MANAGER_BAR', 'MANAGER_STOCK', 'MANAGER_DRAIN', 'WATER_SELLER', 'BENEVOLE');

create type "public"."USER_ROLE" as enum ('ADMIN', 'MANAGER', 'SUPPLEANT', 'BENEVOLE', 'TEST');

drop policy "Enable read access for all users" on "public"."stock_beers";

drop policy "Enable read access for all users" on "public"."stock_foods";

drop policy "Enable read access for all users" on "public"."stock_materials";

drop policy "Enable read access for all users" on "public"."stock_softs";


  create table "public"."managers" (
    "id" bigint generated by default as identity not null,
    "manager" uuid not null,
    "suppleant" uuid
      );


alter table "public"."managers" enable row level security;

alter table "public"."stock_beers" drop column "bottles_per_crate";

alter table "public"."stock_beers" drop column "stock_crates";

alter table "public"."stock_beers" add column "entity_per_crate" numeric not null default '0'::numeric;

alter table "public"."stock_beers" add column "stock" numeric not null default '0'::numeric;

alter table "public"."stock_foods" drop column "entity_per_box";

alter table "public"."stock_foods" drop column "stock_box";

alter table "public"."stock_foods" add column "entity_per_crate" numeric not null;

alter table "public"."stock_foods" add column "stock" numeric not null default '0'::numeric;

alter table "public"."stock_materials" drop column "entity_per_box";

alter table "public"."stock_materials" drop column "stock_box";

alter table "public"."stock_materials" add column "entity_per_crate" numeric not null;

alter table "public"."stock_materials" add column "stock" numeric not null default '0'::numeric;

alter table "public"."stock_softs" drop column "bottles_per_crate";

alter table "public"."stock_softs" drop column "stock_crates";

alter table "public"."stock_softs" add column "entity_per_crate" numeric not null;

alter table "public"."stock_softs" add column "stock" numeric not null;

alter table "public"."users" add column "role" public."ROLE" not null default 'BENEVOLE'::public."ROLE";

CREATE UNIQUE INDEX managers_pkey ON public.managers USING btree (id);

alter table "public"."managers" add constraint "managers_pkey" PRIMARY KEY using index "managers_pkey";

alter table "public"."managers" add constraint "managers_id_fkey" FOREIGN KEY (id) REFERENCES public.locations(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."managers" validate constraint "managers_id_fkey";

alter table "public"."managers" add constraint "managers_manager_fkey" FOREIGN KEY (manager) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."managers" validate constraint "managers_manager_fkey";

alter table "public"."managers" add constraint "managers_suppleant_fkey" FOREIGN KEY (suppleant) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."managers" validate constraint "managers_suppleant_fkey";

grant delete on table "public"."managers" to "anon";

grant insert on table "public"."managers" to "anon";

grant references on table "public"."managers" to "anon";

grant select on table "public"."managers" to "anon";

grant trigger on table "public"."managers" to "anon";

grant truncate on table "public"."managers" to "anon";

grant update on table "public"."managers" to "anon";

grant delete on table "public"."managers" to "authenticated";

grant insert on table "public"."managers" to "authenticated";

grant references on table "public"."managers" to "authenticated";

grant select on table "public"."managers" to "authenticated";

grant trigger on table "public"."managers" to "authenticated";

grant truncate on table "public"."managers" to "authenticated";

grant update on table "public"."managers" to "authenticated";

grant delete on table "public"."managers" to "service_role";

grant insert on table "public"."managers" to "service_role";

grant references on table "public"."managers" to "service_role";

grant select on table "public"."managers" to "service_role";

grant trigger on table "public"."managers" to "service_role";

grant truncate on table "public"."managers" to "service_role";

grant update on table "public"."managers" to "service_role";


  create policy "Enable read access for authenticated users"
  on "public"."stock_beers"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable read access for authenticated users"
  on "public"."stock_foods"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable read access for authenticated users"
  on "public"."stock_materials"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable read access for authenticated users"
  on "public"."stock_softs"
  as permissive
  for select
  to authenticated
using (true);



